market_research:
  description: >
    Create a lean research brief using only essential points.
    Focus: market trends (3 bullets), 3 competitors (1 line each),
    top 3 customer pains, and top 3 opportunities.
    <Product Name>{product_name}</Product Name>
    <Product Description>{product_description}</Product Description>
    <Target Audience>{target_audience}</Target Audience>
    <Budget>{budget}</Budget>
    Current date: {current_date}
  expected_output: >
    Markdown brief ≤400 words: Trends, Competitors, Pains, Opportunities, 3 quick wins.

prepare_marketing_strategy:
  description: >
    Produce a crisp strategy for 1 week. Use the research brief as context.
    Include: positioning (2 lines), ICP (3 bullets), channels (≤3),
    budget split (percentages), and a 7-day plan with 3 blogs, 2 reels,
    5 posts. Keep it short and actionable.
    <Product Name>{product_name}</Product Name>
    <Product Description>{product_description}</Product Description>
    <Target Audience>{target_audience}</Target Audience>
    Current date: {current_date}
  expected_output: >
    Markdown strategy ≤500 words. Save to 'resources/drafts/marketing_strategy.md'.

create_content_calendar:
  description: >
    Build a 1-week calendar (dates, topic, asset type, owner).
    Ensure topics match the strategy. Keep each line terse.
    <Product Name>{product_name}</Product Name>
    <Product Description>{product_description}</Product Description>
    <Target Audience>{target_audience}</Target Audience>
    Current date: {current_date}
  expected_output: >
    Markdown table for 7 days. Save to 'resources/drafts/content_calendar.md'.

prepare_post_drafts:
  description: >
    Draft 5 social posts (LinkedIn, X/Twitter, Instagram) and 1 email.
    Max 120 words each. Include 1 hook + 1 CTA + 2–3 hashtags where relevant.
    <Product Name>{product_name}</Product Name>
    <Product Description>{product_description}</Product Description>
    <Target Audience>{target_audience}</Target Audience>
    Current date: {current_date}
  expected_output: >
    Save each as separate markdown files under 'resources/drafts/posts/'.

prepare_scripts_for_reels:
  description: >
    Create 2 reels scripts (≤90 seconds): hook, 3 beats, CTA, caption.
    Assign to "Video:You", "Edit:You". Keep copy tight.
    <Product Name>{product_name}</Product Name>
    <Product Description>{product_description}</Product Description>
    <Target Audience>{target_audience}</Target Audience>
    Current date: {current_date}
  expected_output: >
    Save 2 .md files under 'resources/drafts/reels/'.

content_research_for_blogs:
  description: >
    Propose 3 blog outlines: title, 5 H2s, key takeaways bullets.
    <Product Name>{product_name}</Product Name>
    <Product Description>{product_description}</Product Description>
    <Target Audience>{target_audience}</Target Audience>
    Current date: {current_date}
  expected_output: >
    Markdown with 3 outlines ≤300 words total.

draft_blogs:
  description: >
    Draft 3 concise blogs (700–900 words each), structured with intro (≤90 words),
    H2 sections, bullets, conclusion. Avoid fluff.
    <Product Name>{product_name}</Product Name>
    <Product Description>{product_description}</Product Description>
    <Target Audience>{target_audience}</Target Audience>
    Current date: {current_date}
  expected_output: >
    Save 3 .md files to 'resources/drafts/blogs/'.

seo_optimization:
  description: >
    For each drafted blog, output: SEO title (≤60 chars), slug, meta (≤150 chars),
    5–8 keywords, and internal link suggestions (relative paths).
    <Product Name>{product_name}</Product Name>
    <Product Description>{product_description}</Product Description>
    <Target Audience>{target_audience}</Target Audience>
    Current date: {current_date}
  expected_output: >
    Save a single 'resources/drafts/blogs/_seo_summary.md' with entries per blog.
